{% set name = "minify-html" %}
{% set version = "0.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/minify_html-{{ version }}.tar.gz
  sha256: fe160954bc12cdb8608437d90264876d4e18abf820d6080a3211d396952340b4

build:
  script_env:
    - PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=0.13
    - pip
  run:
    - python

test:
  imports:
    - minify_html
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wilsonzlin/minify-html
  summary: Extremely fast and smart HTML + JS + CSS minifier
  license: MIT
  license_file: minify-html/LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
